### ISSUE TITLE
Could not add chart repository. Wrong credentials?

### ISSUE THREAD

**Issue by timvol** [nflaig/semantic-release-helm#4]
I'm getting the following error in my pipeline:

```
[9:03:02 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Could not add chart repository. Wrong credentials?
    at /usr/local/lib/node_modules/semantic-release-helm3/node_modules/aggregate-error/index.js:23:11
    at Array.map (<anonymous>)
    at new AggregateError (/usr/local/lib/node_modules/semantic-release-helm3/node_modules/aggregate-error/index.js:13:24)
    at module.exports (/usr/local/lib/node_modules/semantic-release-helm3/lib/verifyConditions.js:84:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async verifyConditions (/usr/local/lib/node_modules/semantic-release-helm3/index.js:9:5)
    at async validator (/usr/local/lib/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as verifyConditions] (/usr/local/lib/node_modules/semantic-release/lib/plugins/index.js:80:11) {
  pluginName: 'semantic-release-helm3'
}
[9:03:02 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: helm repo add semantic-release-helm https://some.gitlab.server/api/v4/projects/349/packages/helm/stable
Error: looks like "https://some.gitlab.server/api/v4/projects/349/packages/helm/stable" is not a valid chart repository or cannot be reached: failed to fetch https://some.gitlab.server/api/v4/projects/349/packages/helm/stable/index.yaml : 401 Unauthorized
```

I tried the same command on my local PC and also got 401. Then I added "--username" and "--password" to the "helm repo add" command and it was able to add the repo. Unfortunately "helm registry login" before calling semantic-release didn't solve my problem. So are we missing these parameters here?

**Comment by timvol** [comment]
Ok, I was able to fix this issue. I was using `REPOSITORY_` env variables instead of `REGISTRY_`
