### ISSUE TITLE
Getting a type error when running the plugin to update a helm repo

### ISSUE THREAD

**Issue by Bh-an** [nflaig/semantic-release-helm#6]
All steps in the plugin pass normally but the publish step gives an error

ERROR LOGS:

```
fix(Values.yml): Removed some redundancy
2022-11-14T12:15:53.611Z semantic-release:commit-analyzer Analyzing with default rules
[12:15:53 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:15:53 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(Values.yml): Removed some redundancy
2022-11-14T12:15:53.612Z semantic-release:commit-analyzer Analyzing with default rules
2022-11-14T12:15:53.613Z semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch'
[12:15:53 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[12:15:53 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: patch release
[12:15:53 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[12:15:53 PM] [semantic-release] › ℹ  The next release version is 1.0.4
[12:15:53 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "semantic-release-helm3"
[12:15:53 PM] [semantic-release] [semantic-release-helm3] › ℹ  Updating Chart.yaml with version 1.0.4 and appVersion 1.0.4.
[12:15:53 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "semantic-release-helm3"
[12:15:55 PM] [semantic-release] › ✔  Created tag v1.0.4
[12:15:55 PM] [semantic-release] › ℹ  Start step "publish" of plugin "semantic-release-helm3"
[12:15:55 PM] [semantic-release] › ✖  Failed step "publish" of plugin "semantic-release-helm3"
[12:15:55 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Invalid Version: [object Promise]
    at new SemVer (/var/lib/jenkins/workspace/New Job/node_modules/semver/classes/semver.js:19:13)
    at compare (/var/lib/jenkins/workspace/New Job/node_modules/semver/functions/compare.js:3:3)
    at Object.gte (/var/lib/jenkins/workspace/New Job/node_modules/semver/functions/gte.js:2:30)
    at publishChartToRegistry (/var/lib/jenkins/workspace/New Job/node_modules/semantic-release-helm3/lib/publish.js:67:24)
    at module.exports (/var/lib/jenkins/workspace/New Job/node_modules/semantic-release-helm3/lib/publish.js:19:19)
    at async publish (/var/lib/jenkins/workspace/New Job/node_modules/semantic-release-helm3/index.js:30:5)
    at async validator (/var/lib/jenkins/workspace/New Job/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /var/lib/jenkins/workspace/New Job/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /var/lib/jenkins/workspace/New Job/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async pluginsConf.<computed> [as publish] (/var/lib/jenkins/workspace/New Job/node_modules/semantic-release/lib/plugins/index.js:80:11) {
  pluginName: 'semantic-release-helm3'
}
TypeError: Invalid Version: [object Promise]
    at new SemVer [90m(/var/lib/jenkins/workspace/New Job/[39mnode_modules/[4msemver[24m/classes/semver.js:19:13[90m)[39m
    at compare [90m(/var/lib/jenkins/workspace/New Job/[39mnode_modules/[4msemver[24m/functions/compare.js:3:3[90m)[39m
    at Object.gte [90m(/var/lib/jenkins/workspace/New Job/[39mnode_modules/[4msemver[24m/functions/gte.js:2:30[90m)[39m
    at publishChartToRegistry [90m(/var/lib/jenkins/workspace/New Job/[39mnode_modules/[4msemantic-release-helm3[24m/lib/publish.js:67:24[90m)[39m
    at module.exports [90m(/var/lib/jenkins/workspace/New Job/[39mnode_modules/[4msemantic-release-helm3[24m/lib/publish.js:19:19[90m)[39m
    at async publish [90m(/var/lib/jenkins/workspace/New Job/[39mnode_modules/[4msemantic-release-helm3[24m/index.js:30:5[90m)[39m
    at async validator [90m(/var/lib/jenkins/workspace/New Job/[39mnode_modules/[4msemantic-release[24m/lib/plugins/normalize.js:34:24[90m)[39m
    at async [90m/var/lib/jenkins/workspace/New Job/[39mnode_modules/[4msemantic-release[24m/lib/plugins/pipeline.js:37:34
    at async [90m/var/lib/jenkins/workspace/New Job/[39mnode_modules/[4msemantic-release[24m/lib/plugins/pipeline.js:31:3
    at async pluginsConf.<computed> [as publish] [90m(/var/lib/jenkins/workspace/New Job/[39mnode_modules/[4msemantic-release[24m/lib/plugins/index.js:80:11[90m)[39m {
  pluginName: [32m'semantic-release-helm3'[39m
}
```
My .releaserc.yml file:

```
{

"branches": ["main"],

  "plugins": [
    [
      "semantic-release-helm3",
      {
        chartPath: './',
        registry: 'https://github.com/csye7125-fall2022-group01/helm-chart'
      }
    ]
  ]
}
```

In case it is relevant I'm running the plugin on a jenkins ci environment 

If you need any more details i'd be happy to provide them !

**Comment by nflaig** [comment]
@Bh-an thanks for reporting the issue, it should be fixed in version `2.3.4`. Let me know if you still face any issues.
